In [ ]:
import os,logging,sys,random
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.layers import Flatten,Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

logging.disable(logging.WARNING)

%load_ext autoreload
%autoreload 2
%matplotlib inline
%load_ext tensorboard

In [ ]:
 def get_model_seq():
  model=tf.keras.Sequential()
  model.add(Flatten(input_shape=(28,28)))
  model.add(Dense(128, activation=tf.nn.relu))
  model.add(Dense(10, activation=tf.nn.softmax))
  return model

In [ ]:
def get_model():
  input_size=(28,28,1)
  inputs = tf.keras.Input(shape=input_size)
  x1=Flatten(input_shape=(28,28))(inputs)
  x2 = Dense(128, activation=tf.nn.relu)(x1)
  outputs = Dense(10, activation=tf.nn.softmax)(x2)
  model = tf.keras.Model(inputs=inputs, outputs=outputs)
  return model

In [ ]:
# Load the fashion-mnist pre-shuffled train data and test data
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()
print("x_train shape:", x_train.shape, "y_train shape:", y_train.shape)

x_train shape: (60000, 28, 28) y_train shape: (60000,)


In [ ]:
x_train=np.expand_dims(x_train,axis=-1)
x_test=np.expand_dims(x_test,axis=-1)

In [ ]:
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

In [ ]:
train_x,val_x,train_y,val_y=train_test_split(x_train,y_train,test_size=0.3,random_state=5)

In [ ]:
val_y[0]

2

In [ ]:
train_y_one_hot=to_categorical(train_y)
val_y_one_hot=to_categorical(val_y)
y_test_one_hot=to_categorical(y_test)

In [ ]:
val_y_one_hot[0]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
model = get_model()

In [ ]:
metrics='accuracy'
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=metrics)

In [ ]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 28, 28, 1)]       0         
_________________________________________________________________
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(train_x, train_y_one_hot,validation_data=(val_x,val_y_one_hot),epochs=1)

1313/1313 [==============================] - 4s 3ms/step - loss: 0.8085 - accuracy: 0.7355 - val_loss: 0.6056 - val_accuracy: 0.8014


In [ ]:
model.save('model.h5')

In [ ]:
test_loss, test_acc = model.evaluate(x_test,y_test_one_hot)

313/313 [==============================] - 1s 2ms/step - loss: 0.6227 - accuracy: 0.7890


In [ ]:
test_pred = model.predict(x_test)

In [ ]:
print("Test Accuracy:",test_acc)

Test Accuracy: 0.7889999747276306


In [ ]:
out=np.argmax(test_pred,axis=-1)

In [ ]:
confusion_matrix(y_test,out)

array([[745,   7,  25,  90,   3,   3, 105,   0,  22,   0],
       [  3, 918,  20,  48,   3,   0,   6,   0,   2,   0],
       [  9,   1, 785,  12,  90,   2,  85,   0,  16,   0],
       [ 24,   9,  22, 871,  15,   1,  52,   0,   6,   0],
       [  0,   3, 260,  65, 544,   0, 116,   0,  12,   0],
       [  1,   0,   0,   3,   0, 809,   0, 106,  10,  71],
       [157,   1, 171,  65,  86,   2, 480,   0,  38,   0],
       [  0,   0,   0,   0,   0,  32,   0, 886,   0,  82],
       [  1,   1,  19,  15,   2,   8,  15,  12, 925,   2],
       [  0,   0,   0,   2,   0,  13,   0,  57,   1, 927]])

In [ ]:
#Using Sequential API

model = get_model_seq()
metrics='accuracy'
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=metrics)
model.summary()
model.fit(train_x, train_y_one_hot,validation_data=(val_x,val_y_one_hot),epochs=1)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_6 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_12 (Dense)             (None, 128)               100480    
_________________________________________________________________
dense_13 (Dense)             (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
1313/1313 [==============================] - 5s 4ms/step - loss: 0.8006 - accuracy: 0.7427 - val_loss: 0.6054 - val_accuracy: 0.7977


In [ ]:
test_loss, test_acc = model.evaluate(x_test,y_test_one_hot)
test_pred = model.predict(x_test)
print("Test Accuracy:",test_acc)
out=np.argmax(test_pred,axis=-1)
confusion_matrix(y_test,out)

313/313 [==============================] - 1s 3ms/step - loss: 0.6194 - accuracy: 0.7893
Test Accuracy: 0.7893000245094299


array([[850,  10,  13,  38,  13,   1,  56,   0,  19,   0],
       [  8, 939,  15,  26,   9,   0,   1,   0,   2,   0],
       [ 25,   1, 627,   7, 275,   1,  52,   0,  12,   0],
       [ 66,  25,  14, 762,  89,   1,  39,   0,   4,   0],
       [  1,   8,  73,  17, 869,   0,  26,   0,   6,   0],
       [  0,   1,   0,   0,   0, 859,   0,  66,   8,  66],
       [240,   3, 151,  22, 266,   0, 283,   0,  35,   0],
       [  0,   0,   0,   0,   0,  55,   0, 827,   0, 118],
       [  2,   1,  17,  10,   6,   9,  15,   9, 929,   2],
       [  0,   0,   0,   0,   0,  14,   0,  37,   1, 948]])